site_name: Acton Business Review 
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
nav:
        - 'Customers & Sales':
                - customersshoes.md
                - haggling.md
                - insidemind.md
                - customerbehavior.md
                - dealingwithcompetition.md
                - targetingcustomers.md
                - pricingseasons.md
                - artofpricing1.md
        - Operations: operations.md
        - Robo Rush: roborush.md

